name: Laravel Code Analysis and Fix

on:
  pull_request:
    branches:
      - main-dev
  workflow_dispatch:

jobs:
  code-analysis-and-fix:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, bcmath, intl, pcntl
          coverage: none

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --working-dir=InitialProject/src

      # Install PHPStan
      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan --working-dir=InitialProject/src

      # Run PHPStan (Code Check)
      - name: Run PHPStan
        run: |
          php InitialProject/src/vendor/bin/phpstan analyse InitialProject/src --level=max || true

      # Install Laravel Pint
      - name: Install Laravel Pint
        run: composer require --dev laravel/pint --working-dir=InitialProject/src

      # Run Laravel Pint (Auto Fix)
      - name: Run Laravel Pint
        run: php InitialProject/src/vendor/bin/pint --verbose || true

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "Witchakorn Boonprakom"
          git config --global user.email "witchakorn.b@kkumail.com"
          git add .
          git commit -m "Auto-fixed code style using Laravel Pint and PHPStan suggestions" || echo "No changes to commit"
          git push origin main-dev || true
