name: Laravel CI

on:
  push:
    branches:
      - main
      - main-dev
  pull_request:
    branches:
      - main
      - main-dev

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, bcmath, intl, pcntl
          coverage: none

      # Install Composer dependencies
      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-suggest --working-dir=InitialProject/src

      # Install PHPStan
      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan --working-dir=InitialProject/src

      # Install Laravel Pint
      - name: Install Laravel Pint
        run: composer require --dev laravel/pint --working-dir=InitialProject/src

      # Install PHPUnit
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit --working-dir=InitialProject/src

      # Setup application environment
      - name: Setup .env
        run: cp InitialProject/src/.env.example InitialProject/src/.env

      # Generate application key
      - name: Generate application key
        run: php InitialProject/src/artisan key:generate

      # Run database migrations
      - name: Run database migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /tmp/database.sqlite
        run: |
          touch /tmp/database.sqlite
          php InitialProject/src/artisan migrate --force

      # Run PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=max --memory-limit=1G --working-dir=InitialProject/src

      # Run Laravel Pint
      - name: Run Laravel Pint
        run: vendor/bin/pint --test --working-dir=InitialProject/src

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --working-dir=InitialProject/src
