name: Laravel CI

on:
  push:
    branches:
      - main
      - main-dev
  pull_request:
    branches:
      - main
      - main-dev

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, bcmath, intl, pcntl
          coverage: none

      # Install Composer dependencies
      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-suggest --working-dir=InitialProject/src

      # Setup application environment
      - name: Setup .env
        run: cp InitialProject/src/.env.example InitialProject/src/.env

      # Generate application key
      - name: Generate application key
        run: php InitialProject/src/artisan key:generate

      # Run database migrations
      - name: Setup SQLite database for testing
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /tmp/database.sqlite
        run: |
          touch /tmp/database.sqlite
          php InitialProject/src/artisan migrate --force

      # # Seed database (optional)
      # - name: Seed database
      #   run: php InitialProject/src/artisan db:seed

      # Run Laravel tests
      - name: Run Laravel tests
        run: php InitialProject/src/artisan test --verbose --no-interaction
