name: Laravel CI

on:
  push:
    branches:
      - main-dev
      - main
  pull_request:
    branches:
      - main-dev
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, bcmath, intl, pcntl
          coverage: none

      # Install Composer dependencies
      - name: Install Composer
        run: cd InitialProject/src && composer install --prefer-dist --no-progress --no-suggest

      # Install PHPStan
      - name: Install PHPStan
        run: composer require --dev phpstan/phpstan

      # Install Laravel Pint
      - name: Install Laravel Pint
        run: composer require --dev laravel/pint

      # Install PHPUnit
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit

      # Setup application environment
      - name: Setup .env
        run: cd InitialProject/src && cp .env.example .env

      # Generate application key
      - name: Generate application key
        run: cd InitialProject/src && php artisan key:generate

      # Run database migrations
      - name: Run database migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: /tmp/database.sqlite
        run: |
          cd InitialProject/src
          touch /tmp/database.sqlite
          php artisan migrate --force

      # Run PHPStan
      - name: Run PHPStan
        run: cd InitialProject/src && vendor/bin/phpstan analyse --level=max --memory-limit=1G

      # Run Laravel Pint
      - name: Run Laravel Pint
        run: cd InitialProject/src && vendor/bin/pint --test

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: cd InitialProject/src && vendor/bin/phpunit
