name: Laravel CI

on:
  push:
    branches:
      - main
      - main-dev
  pull_request:
    branches:
      - main
      - main-dev

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pcntl, pdo_mysql
          coverage: none

      # Install Composer dependencies
      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-interaction --working-dir=InitialProject/src

      # Create and configure .env
      - name: Configure .env
        run: |
          cp InitialProject/src/.env.example InitialProject/src/.env
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=mysql/' InitialProject/src/.env
          sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' InitialProject/src/.env
          sed -i 's/^DB_PORT=.*/DB_PORT=3306/' InitialProject/src/.env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=laravel_test/' InitialProject/src/.env
          sed -i 's/^DB_USERNAME=.*/DB_USERNAME=root/' InitialProject/src/.env
          sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=password/' InitialProject/src/.env

      # Generate application key
      - name: Generate application key
        working-directory: InitialProject/src
        run: php artisan key:generate

      # Import database.sql if it exists
      - name: Import database.sql if it exists
        run: |
          if [ -f InitialProject/src/database.sql ]; then
            mysql -h127.0.0.1 -uroot -ppassword laravel_test < InitialProject/src/database.sql
          fi

      # Run database migrations
      - name: Run database migrations
        working-directory: InitialProject/src
        run: php artisan migrate --force

      # Run Laravel tests
      - name: Run Laravel tests
        working-directory: InitialProject/src
        run: php artisan test --verbose --no-interaction

      # Run code quality checks
      - name: Run code quality checks
        working-directory: InitialProject/src
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear
          
      # Verify build artifacts
      - name: Verify build artifacts
        working-directory: InitialProject/src
        run: |
          php artisan --version
          php artisan route:list
          
      # Build verification complete
      - name: Build verification complete
        run: echo "Build verification completed successfully. No deployment will be performed."
