name: Laravel CI

on:
  push:
    branches:
      - main
      - main-dev
  pull_request:
    branches:
      - main
      - main-dev

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, bcmath, intl, pcntl
          coverage: none

      # Install Composer dependencies
      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-suggest --working-dir=InitialProject/src

      # Create and configure .env
      - name: Configure .env
        run: |
          cp InitialProject/src/.env.example InitialProject/src/.env
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' InitialProject/src/.env
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=\/tmp\/database.sqlite/' InitialProject/src/.env

      # Generate application key
      - name: Generate application key
        working-directory: InitialProject/src
        run: php artisan key:generate

      # Setup SQLite database
      # - name: Setup SQLite database for testing
      #   working-directory: InitialProject/src
      #   run: |
      #     touch /tmp/database.sqlite
      #     php artisan migrate --force

      # Run Laravel tests
      - name: Run Laravel tests
        working-directory: InitialProject/src
        run: php artisan test --verbose --no-interaction
